#!/bin/bash

echo "🚀 Activador de GitHub Pages para NeuroAsistente TDAH"
echo "======================================================"

echo ""
echo "📋 PASOS PARA ACTIVAR GITHUB PAGES:"
echo ""
echo "1. Ve a: https://github.com/cuervoc-openclaw/TDAH-DASHBOARD"
echo "2. Haz clic en 'Settings' (pestaña superior)"
echo "3. En el menú izquierdo, selecciona 'Pages'"
echo "4. En 'Source', selecciona:"
echo "   - Branch: main"
echo "   - Folder: /frontend/dist"
echo "5. Haz clic en 'Save'"
echo ""
echo "⏳ GitHub hará:"
echo "   - Build automático del proyecto"
echo "   - Deploy a GitHub Pages"
echo "   - URL: https://cuervoc-openclaw.github.io/TDAH-DASHBOARD/"
echo ""
echo "📊 Para verificar el deploy:"
echo "1. Ve a: https://github.com/cuervoc-openclaw/TDAH-DASHBOARD/actions"
echo "2. Verifica que el workflow 'Deploy to GitHub Pages' se ejecute"
echo "3. Espera 2-3 minutos"
echo "4. Abre la URL en tu navegador"
echo ""
echo "🔧 Si hay problemas:"
echo "1. Revisa los logs en GitHub Actions"
echo "2. Asegúrate de que la carpeta /frontend/dist exista"
echo "3. Verifica que el workflow esté configurado"
echo ""
echo "🎯 Ventajas de GitHub Pages:"
echo "✅ Gratis"
echo "✅ Automático (con cada push)"
echo "✅ Sin configuración compleja"
echo "✅ Integrado con GitHub"
echo ""
echo "🚀 ¿Listo para activarlo?"